#ifndef ZNCONSTANTS_H
#define ZNCONSTANTS_H

#define ZN_APP_TITLE wxT("Web Sailor : Event Hub Message Sender")
#define ZN_APP_VERSION wxT("0.0.1")

enum
{
    ID_ZN_FRAME = 1,
    ID_ZN_PANEL,

    ID_ZN_QUIT,
    ID_ZN_ABOUT,

    ID_ZN_TXT_SERVICE_BUS_NAMESPACE,
    ID_ZN_TXT_EVENT_HUB_NAME,

    ID_ZN_TXT_SHARED_ACCESS_POLICY_NAME,
    ID_ZN_TXT_SHARED_ACCESS_POLICY_KEY,

    ID_ZN_TXT_USER_MESSAGE,
    ID_ZN_BTN_SEND_MESSAGE,
    ID_ZN_BTN_SET_SAMPLE_MESSAGE,
    ID_ZN_BTN_CLEAR_MESSAGE,

    ID_ZN_TXT_STATUS_MESSAGE,
    ID_ZN_BTN_CLEAR_STATUS_MESSAGE
};

#endif
